import {default as Area} from "./Charts/Area"
import {default as Bar} from "./Charts/Bar"
import {default as ColorMapping} from "./Charts/ColorMapping"
import {default as Financial} from "./Charts/Financial"
import {default as Line} from "./Charts/Line"
import {default as Pie} from "./Charts/Pie"
import {default as Pyramid} from "./Charts/Pyramid"
import {default as Stacked} from "./Charts/Stacked"
import {default as Calendar} from "./Calendar"
import {default as ColorPicker} from "./ColorPicker"
import {default as Customer} from "./Customer"
import {default as Ecommerce} from "./Ecommerce"
import {default as Editor} from "./Editor"
import {default as Employees} from "./Employees"
import {default as Kanban} from "./Kanban"
import { default as Orders } from "./Orders"

export {Ecommerce, Area, Bar, ColorMapping, Financial, Line, Pie, Pyramid, Stacked, Calendar, ColorPicker, Customer, Editor, Employees, Kanban, Orders }